spring:
  profiles:
    active: '@active.profile@'
  data:
    rest:
      base-path: api/rest
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      roles: USER
      show-details: when_authorized